application: pristine-glass-607
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /login/.*
  script: unearth.app
  login: required

- url: /.*
  script: unearth.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest