application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

# Handler for front page
- url: /
  script: front.application

# All other pages that require login
- url: /.*
  script: unearthlogin.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest